/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Attr: typeof import('./src/components/panles/Attr.vue')['default']
    Attributes: typeof import('./src/components/panles/Attributes.vue')['default']
    CameraAttr: typeof import('./src/components/panles/CameraAttr.vue')['default']
    copy: typeof import('./src/components/panles/Attributes copy.vue')['default']
    Geom: typeof import('./src/components/panles/Geom.vue')['default']
    GeometryAttr: typeof import('./src/components/panles/GeometryAttr.vue')['default']
    GeometryAttrr: typeof import('./src/components/panles/GeometryAttrr.vue')['default']
    HelperAttributes: typeof import('./src/components/panles/HelperAttributes.vue')['default']
    LeftEditPanle: typeof import('./src/components/LeftEditPanle.vue')['default']
    MaterialAttr: typeof import('./src/components/panles/MaterialAttr.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NFlex: typeof import('naive-ui')['NFlex']
    NFloatButton: typeof import('naive-ui')['NFloatButton']
    NFloatButtonGroup: typeof import('naive-ui')['NFloatButtonGroup']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NImageGroup: typeof import('naive-ui')['NImageGroup']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSplit: typeof import('naive-ui')['NSplit']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NTree: typeof import('naive-ui')['NTree']
    NUpload: typeof import('naive-ui')['NUpload']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scene: typeof import('./src/components/Scene.vue')['default']
    SceneAttr: typeof import('./src/components/panles/SceneAttr.vue')['default']
  }
}
